server:
  port: 1000
spring:
  application:
    name: springboot-config
  cloud:
    config:
     server:
       git:
          uri: https://github.com/xiaoyaoll/neuer.git
          search-paths: config-dev
     label: dev #\u586B\u5199\u9ED8\u8BA4\u5206\u652F
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:7002/eureka
