server:
  port: 80
spring:
  application:
    name: consumer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002:7002/eureka
ribbon:
 ConnectTimeout: 5000
 ReadTimeout: 5000


